### ISSUE TITLE
Can Fractal Chains be used in a Production Setting? What are some limitations? 

### ISSUE THREAD

**Issue by nathanawmk** [fractalide/fractalchains#4]
Hello! Can Fractal Chains be used in a Production Setting? What are some limitations? 

Nathan Aw

**Comment by sjmackenzie** [comment]
No sadly not yet! Still a long way to go! (closing)

**Comment by nathanawmk** [comment]
How can one like myself contribute? Nathan Aw

**Comment by sjmackenzie** [comment]
Need folks with good programming skill or a large budget, which I'll control, to hire programmers.

**Comment by nathanawmk** [comment]
Sounds like what i can do.

Nathan Aw

On 28 Feb 2018 6:32 pm, "Stewart Mackenzie" <notifications@github.com>
wrote:

Need folks with good programming skill or a large budget, which I'll
control, to hire programmers.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fractalide/fractalchains/issues/4#issuecomment-369197136>,
or mute the thread

**Comment by sjmackenzie** [comment]
Great, please email me then.

>

**Comment by nathanawmk** [comment]
I can't locate your email. Please share with me? Are you working with
Silvio Micali by any chance?

Regards,

Nathan Aw
https://sg.linkedin.com/in/awnathan

http://www.nasdaq.com/article/guest-post-understanding-the-limits-and-potential-of-blockchain-technology-cm874892

https://www.hyperledger.org/blog/2017/12/05/developer-showcase-series-nathan-aw-ntt-data

https://bitcoinmagazine.com/authors/nathan-aw/

https://github.com/nathanawmk

On Wed, Feb 28, 2018 at 6:54 PM, Stewart Mackenzie <notifications@github.com
